{{- if .Values.appConf.enable_ui }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freqtrade
spec:
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: freqtrade-ui
            port:
              number: 8080
---
{{- end }}
