apiVersion: v1
kind: ConfigMap
metadata:
  name: freqtrade-strategies
data:
{{- if .Values.strategies }}
{{ .Values.strategies | toYaml | indent 2 }}
{{- else }}
{{ (.Files.Glob "strategies/*").AsConfig | indent 2 }}
{{- end }}
